### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by corysimmons**

### CODE REVIEW

**Comment by ai** [comment]
I will take a logo from this PR and recommit it manually from Maria name

**Comment by 1j01** [comment]
"SugarCSS", as in `scss`?

**Comment by ai** [comment]
Done https://github.com/postcss/sugarss/commit/b477689fd25fdf7206ad869cfa8acb47d0e0595d

**Comment by ai** [comment]
And final step https://github.com/postcss/sugarss/commit/72a0e6a4b5d4beec7a87212c6321344da216367d

**Pull request closed without merging**
