### PR TITLE
Update logo text

### PR DESCRIPTION
**Pull request by 1j01**
* Update logo text to SugarSS
+ Fix the dots going off the cube and one of the corners of the cube (only visible in high definition)
+ Use a relative URL for the logo (don't need to use `gh-pages` for this)

### CODE REVIEW

**Comment by ai** [comment]
You pushed only relative URL :).

Sorry, but we need `gh-pages` for it. For example, npm show same `README.md` content and image will be missed there with relative URL.

**Comment by 1j01** [comment]
Looks like that [used to be true](https://github.com/npm/newww/issues/183), but it should work now.

**Comment by 1j01** [comment]
Trust me, I've published images with relative URLs to npm before, e.g. [project-nexus](https://www.npmjs.com/package/project-nexus).

**Comment by ai** [comment]
I tried and it doesn’t work :(
vnidjvh

You can see it even in your fork https://github.com/1j01/sugarss/tree/updated-logo

**Comment by 1j01** [comment]
Oh man, apparently it [doesn't work with svg](https://github.com/isaacs/github/issues/316). That's pretty sad. I guess I'll make another PR.

**Pull request closed without merging**
