### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by corysimmons**
Not sure if this creates new branch or will kill master. Probably kill master.

Need gh-pages

### CODE REVIEW

**Comment by ai** [comment]
Oops, this PR is broken, because it delete all other files

**Comment by ai** [comment]
We need just a PR with `logo.svg` to `master`. But:

1. Do not forget to compress it with `svgo`.
2. Can Maria do it to save her name in history? (we also will write her name in `alt` attribute)

**Comment by corysimmons** [comment]
@ai I don't think Maria has GitHub or knows how to use it. Would it be possible to add her name to the bottom of the README? Something like `Logo by Maria Keller` where her name is linked to her dribbble or something?

**Comment by ai** [comment]
@corysimmons no problem, I will make a commit from her name. And I will add her name to README.

Can you send me SVG by email?

**Pull request closed without merging**
